### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ghost** [FunCraftNetwork/NuclearMusic#3]
This plugin seems like I can import songs from my library... Is that possible?

**Comment by Snake1999** [comment]
You're right, Just put your nbs file into /NuclearMusic/tracks/xxxx.nbs, and place a note block in game, and use diamond hoe to toggle it.

**Comment by Lucario2** [comment]
WOW.

**Comment by Lucario2** [comment]
Okay!!

**Comment by Lucario2** [comment]
Is there a way to just broadcast the music to the entire server?

**Comment by ghost** [comment]
I don't know what nbs is. is it the kind of music? the file extension to the music? I don't have a file called track

**Comment by ghost** [comment]
Can you make a live music streamer? That streams mp3 music?

**Comment by Lucario2** [comment]
I have very fast internet and 100mbps speed i can handle it

**Comment by Snake1999** [comment]
Use Minecraft NoteBlock Studio.

**Comment by ghost** [comment]
Dude, I don't have a file Called track.
